# Generated by Django 2.2.1 on 2019-05-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relative_path', models.CharField(max_length=300)),
                ('is_ok', models.BooleanField(default=False)),
            ],
        ),
    ]
